[package]
name = "gpui-calc"
description = "GPUI Calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "ba8aba4d17e93fe24a0b8db51dd41fd7cca40a72" }
anyhow = "1.0.57"
rust-embed = { version = "8.0", features = ["include-exclude"] }

[[bin]]
name = "gpui-calc"
path = "src/main.rs"

[package.metadata.bundle]
name = "GPUI Calculator"
identifier = "com.ndunnett.gpuicalc"
osx_minimum_system_version = "10.15.7"
